import { writeFileSync } from "node:fs";
import { runAgent } from "@/lib/agent/orchestrator";
import { getScene } from "@fixtures/scenes";

/**
 * Regenerates docs/example-agent-trace.json from real runs against the committed
 * demo fixtures, so the published trace can never drift from what the code does.
 *
 * Usage: npm run trace:generate
 */
async function main() {
  const runs = [];
  for (const [sid, dir, dest, downtown, msg] of [
    [
      "outbound-11-wins",
      "to-campus",
      "science-hill",
      false,
      "I'm on the 35 from Scotts Valley. Which bus should I transfer to for campus?",
    ],
    [
      "outbound-11-ghost",
      "to-campus",
      "science-hill",
      true,
      "The 11 never showed up. What should I do?",
    ],
    [
      "return-long-wait",
      "to-home",
      undefined,
      true,
      "The next 35 is ages away - where can I hang out without missing it?",
    ],
  ] as const) {
    const s = getScene(sid)!;
    const r = await runAgent({
      message: msg,
      direction: dir as never,
      destinationKey: dest,
      snapshot: s.build(s.anchorMs),
      nowMs: s.anchorMs,
      demo: true,
      alreadyDowntown: downtown,
    });
    runs.push({
      scene: sid,
      sceneTitle: s.title,
      riderMessage: msg,
      sceneClockIso: new Date(s.anchorMs).toISOString(),
      explanationMode: r.explanationMode,
      model: r.model,
      engineVersion: r.engineVersion,
      trace: r.trace,
      recommendation: r.recommendation
        ? {
            action: r.recommendation.action,
            headline: r.recommendation.headline,
            subhead: r.recommendation.subhead,
            departureIso: r.recommendation.departureIso,
            leaveByIso: r.recommendation.leaveByIso,
            reevaluateAtIso: r.recommendation.reevaluateAtIso,
            backupPlan: r.recommendation.backupPlan,
            blockedReasons: r.recommendation.blockedReasons,
          }
        : null,
      riderFacingMessage: r.message,
    });
  }

  const out = {
    _comment: [
      "Sanitised CruzSync agent traces, generated by `tsx scripts/gen-trace.ts` from real runs",
      "against the committed demo fixtures. Contains NO chain-of-thought: only the tools the agent",
      "called, redacted arguments, timings, sources and one-line result summaries.",
      "Rider free text is redacted inside `args`; the top-level `riderMessage` is included",
      "deliberately because it is the demo prompt, not private user data.",
    ].join(" "),
    generatedAt: new Date().toISOString(),
    note: 'origin "fixture" means the underlying real-time evidence is labelled demonstration data.',
    runs,
  };
  writeFileSync(
    "docs/example-agent-trace.json",
    JSON.stringify(out, null, 2) + "\n",
  );
  console.log("wrote docs/example-agent-trace.json");
  runs.forEach((r) =>
    console.log(
      " ",
      r.scene.padEnd(20),
      r.trace.length + " calls",
      "->",
      r.recommendation?.action,
    ),
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
